### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iamevaristus**

### CODE REVIEW

**Comment by jumalaw98** [comment]
No changes done

**Review by jumalaw98 — APPROVED** [review]

**Comment by jumalaw98** [comment]
Hello @iamevaristus  for the collaborators part, can we make it automatically generated from the contribution graph, once someone has made a push?

**Comment by iamevaristus** [comment]
> Hello @iamevaristus for the collaborators part, can we make it automatically generated from the contribution graph, once someone has made a push?

That's important. There is a need to measure contribution for what we wanna use that analytics for in the future

**Comment by jumalaw98** [comment]
Noted

**Pull request merged**
